[workspace]
members = [
    # "tools"
]
[package]
name = "joker"
version = "0.1.0"
edition = "2021"
authors = ["redskaber@foxmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tools = { path = "tools" }
